apiVersion: apps/v1
kind: Deployment
metadata:
  name: p17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p17
  template:
    metadata:
      labels:
        app: p17
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p17
        ports:
        - containerPort: 80
